### ISSUE TITLE
PWD Docker instructions...

### ISSUE THREAD

**Issue by mpanthofer** [mikegcoleman/hybrid-workshop#16]
In my browser (Chrome/Win 10) the PWD session information was hiding below the terminal window. 

Step 1.2.2 Reads...
When prompted enter your username and password (these can be found at the top of your main PWD screen). The UCP web interface should load up in your web browser.

For my browser it should be...
When prompted enter your username and password (these can be found below the console terminal on the right side of PWD screen). The UCP web interface should load up in your web browser.

**Comment by mpanthofer** [comment]
I assume you know about this and worse case we talk around it as a PWD limitation (and it's still encrypted), but thought I post just in case.

> Unauthorized users can access the following node since it is listening on an external port: manager1:2376

![hybridws-pwd-ucp-banner](https://user-images.githubusercontent.com/4315108/30700335-ee5b8858-9eac-11e7-897c-c5dfeb269b9f.GIF)

**Comment by mikegcoleman** [comment]
Thanks for taking time to review the lab guide / pwd environment!

re: Comment #1: We just updated the PWD setup to put the session info below (having them up top caused scrolling issues in the console), I am going to be updating the instructions to match. 

re: Comment #2: This comment in the lab guide is in reference to that warning. I'll add a screen shot so folks know. 

![screen shot 2017-09-21 at 9 30 41 am](https://user-images.githubusercontent.com/6797199/30707215-a5e528b0-9eaf-11e7-9b0e-6779ce962836.png)
