### ISSUE TITLE
Windows Update Not...

### ISSUE THREAD

**Issue by zipzit** [mikegcoleman/hybrid-workshop#2]
Apparently when spinning up the Windows worker node (Task 1.2) there is a popup that asks you if you want to update windows.  Apparently this is not a good thing to do.  You get to a place where it is impossible to connect to the node.  

`Unable to connect to remote PC. Please verify Remote Desktop is enabled, the remote PC is turned on and available on the network, and then try again.`

sigh.  

Recommend the instructions be modified to specifically tell the user

DO NOT UPDATE WINDOWS at initial installation when prompted to do so.  HaveANIceDay...

**Comment by mikegcoleman** [comment]
Actually, if you do the update you just have to wait for it to finish. This can take a VERY long time. However, the uber point is well taken: Do NOT update the VM.

**Comment by mikegcoleman** [comment]
@zipzit wanted to also say I added a warning in the instructions to hopefully save other people the hassle Thanks for the comment.
