### ISSUE TITLE
Virtual Machine Roles needs clarity

### ISSUE THREAD

**Issue by jweissig** [mikegcoleman/hybrid-workshop#6]
The README.md has a little block of text that talks about node roles. There are 5 boxes in this lab but the block talks about three nodes. It might make sense to call this `The cluster you will be building will be comprised of three node types (linux manager, linux workers, and windows workers).` This is pretty nit-picky but might benefit from added clarity.

```
Virtual Machine Roles

The cluster you will be building will be comprised of three nodes - a Linux manager, a Linux Worker and a Windows worker. We will also have a linux node and a windows node that will serve as workstations - you'll connect to these machines to do things like build and push docker images.
```

**Comment by mikegcoleman** [comment]
Updated. Thanks!
