### ISSUE TITLE
Task 1.3 minor issue with UI when adding Windows node

### ISSUE THREAD

**Issue by jweissig** [mikegcoleman/hybrid-workshop#9]
The UI in UCP is a little confusing when you want to add a Windows worker node since the select boxes have to be highlighted for Linux & Worker. This might trip some users up.

![screen shot 2017-08-18 at 11 45 36 pm](https://user-images.githubusercontent.com/1945248/29484344-5dffc292-8471-11e7-8f7a-c751a03301e6.png)

If they select Windows they are shown a link to the docs. The select boxes have to be on Linux/Worker for the command to be shown. Its the same command for both Linux & Windows.

![screen shot 2017-08-19 at 12 01 32 am](https://user-images.githubusercontent.com/1945248/29484357-a05bf444-8471-11e7-8781-c0a5232d983e.png)

This is more of just a heads up as a possible gotcha.

**Comment by mikegcoleman** [comment]
I'll add an explanation. 

Background: 
I actually filed an issue on this with the dev team around this UI, as it's all pretty confusing. In the lab I actually do all the prerequisite steps that the "Windows" UI mentions, but the only way to get the Join Token is to go back to "Linux".
